default['audit']['reporter'] = 'chef-server-automate'
default['audit']['fetcher'] = 'chef-server'
default['audit']['profiles'] = {}
#default['audit']['profiles']['linux_baseline'] = {'compliance': 'admin/linux-baseline'}
#default['audit']['profiles']['windows_baseline'] = {'compliance': 'admin/windows-baseline'}
default['chef_client']['interval'] = '60'
default['chef_client']['splay'] = '5'
default['chef_client']['config']['client_fork'] = true
default['chef_client']['config']['ssl_verify_mode'] = ':verify_none'
default['chef_client']['config']['verify_api_cert'] = false
default['chef_client']['chef_license'] = 'accept'
default['chef_client']['task']['frequency_modifier'] = 1
